#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ $# -ne 2 ]
then
        echo "Bad # args.  Blech!" >&2
        exit 1
fi

VENV_DIR=$(realpath.exe --canonicalize-missing $SCRIPT_DIR/../../install/venv/)

# The first argument is the path to python-config.py, ignore it.

case "$2" in
--includes) echo "-I$SCRIPT_DIR/python-dev/include" ;;
--ldflags) echo "-L$SCRIPT_DIR/python-dev/libs -lpython312" ;;
--exec-prefix) echo "$VENV_DIR" ;;
--prefix) echo "$VENV_DIR" ;;
*) echo "Bad arg $2.  Blech!" >&2 ; exit 1 ;;
esac

exit 0